name: CI - Build and Test CatalogService

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Publish application
        run: dotnet publish Services/CatalogService/Catalog.API/Catalog.API.csproj -c Release -o published

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: catalogservice-api
          path: published/
