services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrong!Passw0rd1
    ports:
      - "1435:1433"
    networks:
      - micro_net

  catalog_api:
    build:
      context: ./Services/CatalogService/
      dockerfile: Dockerfile
    container_name: catalog_api_container
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=CatalogDb;User Id=sa;Password=MyStrong!Passw0rd1;TrustServerCertificate=True
      # Hostname del broker que usaremos dentro de la red de Docker
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
    depends_on:
      - sqlserver
      - rabbitmq   # espera a que el broker esté arriba
    networks:
      - micro_net

  ordering_api:
    build:
      context: ./Services/OrderingService/
      dockerfile: Dockerfile
    container_name: ordering_api_container
    ports:
      - "5004:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=OrderingDb;User Id=sa;Password=MyStrong!Passw0rd1;TrustServerCertificate=True
      - CatalogService__BaseUrl=http://catalog_api_container:80
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
    depends_on:
      - sqlserver
      - catalog_api
      - rabbitmq   # ordering también necesita el broker
    networks:
      - micro_net

  rabbitmq:
    image: rabbitmq:3.13-management   # imagen con UI de administración
    container_name: rabbitmq
    ports:
      
      - "15673:15672"  # UI de administración en http://localhost:15672 (guest/guest)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - micro_net

networks:
  micro_net:
    driver: bridge